Preamp: 3.65 dB
Filter 1: ON LSC Fc 105.0 Hz Gain -4.0 dB Q 0.40
Filter 2: ON PK Fc 178.9 Hz Gain 12.4 dB Q 1.49
Filter 3: ON PK Fc 261.3 Hz Gain 7.6 dB Q 2.60
Filter 4: ON PK Fc 770.6 Hz Gain -12.9 dB Q 2.37
Filter 5: ON PK Fc 1627.4 Hz Gain -7.7 dB Q 2.15
Filter 6: ON PK Fc 3810.9 Hz Gain -11.7 dB Q 0.73
Filter 7: ON HSC Fc 10000.0 Hz Gain 1.9 dB Q 0.70
