Preamp: 5.50 dB
Filter 1: ON LSC Fc 105.0 Hz Gain -15.7 dB Q 0.70
Filter 2: ON PK Fc 122.1 Hz Gain 14.6 dB Q 0.54
Filter 3: ON PK Fc 616.7 Hz Gain -6.1 dB Q 2.56
Filter 4: ON PK Fc 1239.7 Hz Gain 4.6 dB Q 5.49
Filter 5: ON PK Fc 1561.1 Hz Gain -8.7 dB Q 0.84
Filter 6: ON PK Fc 3625.6 Hz Gain -3.8 dB Q 1.34
